version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  writer:
    build:
      context: ./writer
    container_name: time-writer
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
``
